### PR TITLE
Readme updated

### PR DESCRIPTION
**Pull request by rmurphy-hmcts**
### Change description ###
Readme updated

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by thomaswatsonv1 — APPROVED** [review]
Looks good to me.

**Comment by chris-pateman** [comment]
Writing change requests here:

- This will not just be for CVP. can we remove the name: https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/main.tf#L25
- You do not need the link if provided the content. https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/main.tf#L28
- If these are coming in as Vars do they need to be converted to locals? confuses logic of following where they origin from. https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/main.tf#L4
- can we remove azdo from here as will be used by different pipeline types: https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/main.tf#L62
- script should be located in the module, not a var. https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/main.tf#L27
- can this be sourced from the previous resource output? https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/main.tf#L54
- Can the module schedule for start and stop? if one is not provided then it is not ran. https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/variables.tf#L26
- Should not have CVP code in here and can reuse existing CVP MI. https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/managed_identity.tf#L1
- do not need example of vars and no mention of CVP please. https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/README.md?plain=1#L10
- do not need example of automation account https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/README.md?plain=1#L28
- remove count. https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/README.md?plain=1#L52
- source should be formatted (git@github.com:hmcts/cnp-module-automation-runbook-start-stop-vm?ref=master) https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/README.md?plain=1#L54
- example should be of a basic example not using vars or local but string inputs so they can see the example of the format required. https://github.com/hmcts/cnp-module-automation-runbook-start-stop-vm/blob/38013e32cf10653b025ed910b2ff826931acf14b/README.md?plain=1#L55
- make values generic to any project.
- Add any optional items.
- Can you add `sds-devops` team as write permissions to repo
- Can you add `sds-devops-admin` team as admin permissions to repo
- Can you remove all other team user access please
- Can you add terraform as part of the branching policy
-

**Review by chris-pateman — COMMENTED** [review]
Requests in comments

**Comment by chris-pateman** [comment]
also can you add this github folder with workflow etc:
https://github.com/hmcts/cnp-module-automation-runbook-app-recycle/tree/master/.github

**Pull request merged**
